name: Greeting the user
description: custom action to greet the user
runs: 
  using: "composite"
  steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Welcome user
      run: echo "Hello user..!"
