name: 12-using-outputs
on: [workflow_dispatch]
jobs:
  welcome:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.step1.outputs.NAME }}
    steps:
      - id: step1
        run: echo "NAME=Virat" >> "$GITHUB_OUTPUT"

  goodbye:
    runs-on: ubuntu-latest
    needs: [welcome]
    steps:
      - run: echo "Bye, ${{ needs.welcome.outputs.name }}"

  step2:
    runs-on: ubuntu-latest
    needs: welcome
    steps:
      - name: to test o/p from wlcm job
        run: echo "the name from wlcm job is = ${{ needs.welcome.outputs.name }}"
