name: Simple Workflow

on:
  workflow_dispatch:
    
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Greet user
        uses: ./.github/custom-action/greet-action
        with:
          name: Samarth
